name: facebook_home_page
description: A simple Facebook home page clone.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Core
  provider:
  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.2.1
  # Media & Images
  image_picker:
  cached_network_image:
  # Cloudinary
  cloudinary_public:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
